model:
  name: "autoencoder"
  input_dim: 784
  latent_dim: 128
  hidden_dims: [512, 256]

training:
  num_epochs: 100
  batch_size: 128
  learning_rate: 0.001
  weight_decay: 0.00001
  optimizer: "adam"
  loss_function: "mse"
  scheduler: "step"
  scheduler_params:
    step_size: 30
    gamma: 0.5

data:
  dataset_type: "reconstruction"
  data_dir: "data"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  image_size: 28
  num_workers: 4
  pin_memory: true
  augmentation: false
  noise_level: 0.3

experiment:
  name: "autoencoder_denoising"
  log_dir: "logs/autoencoder"
  checkpoint_dir: "checkpoints/autoencoder"
  save_every: 10
  log_images_every: 5
  device: "auto"
  seed: 42
  resume_from: null
